/*
Navicat Oracle Data Transfer
Oracle Client Version : 12.1.0.2.0

Source Server         : DTSCMS
Source Server Version : 110200
Source Host           : 110.185.100.222:1521
Source Schema         : DTSCMS

Target Server Type    : ORACLE
Target Server Version : 110200
File Encoding         : 65001

Date: 2018-09-15 14:30:09
*/


-- ----------------------------
-- Table structure for SYS_USER
-- ----------------------------
DROP TABLE "DTSCMS"."SYS_USER";
CREATE TABLE "DTSCMS"."SYS_USER" (
"F_ID" VARCHAR2(50 BYTE) NOT NULL ,
"F_ACCOUNT" VARCHAR2(50 BYTE) NULL ,
"F_REALNAME" VARCHAR2(50 BYTE) NULL ,
"F_NICKNAME" VARCHAR2(50 BYTE) NULL ,
"F_HEADICON" VARCHAR2(50 BYTE) NULL ,
"F_GENDER" NUMBER NULL ,
"F_BIRTHDAY" DATE NULL ,
"F_MOBILEPHONE" VARCHAR2(20 BYTE) NULL ,
"F_EMAIL" VARCHAR2(50 BYTE) NULL ,
"F_WECHAT" VARCHAR2(50 BYTE) NULL ,
"F_MANAGERID" VARCHAR2(50 BYTE) NULL ,
"F_SECURITYLEVEL" NUMBER NULL ,
"F_SIGNATURE" VARCHAR2(500 BYTE) NULL ,
"F_ORGANIZEID" VARCHAR2(50 BYTE) NULL ,
"F_DEPARTMENTID" VARCHAR2(500 BYTE) NULL ,
"F_DUTYID" VARCHAR2(500 BYTE) NULL ,
"F_JOBNUMBER" VARCHAR2(50 BYTE) NULL ,
"F_ISADMINISTRATOR" NUMBER NULL ,
"F_SORTCODE" NUMBER NULL ,
"F_DELETEMARK" NUMBER DEFAULT 0  NULL ,
"F_ENABLEDMARK" NUMBER DEFAULT NULL  NULL ,
"F_DESCRIPTION" VARCHAR2(500 BYTE) NULL ,
"F_CREATORTIME" DATE DEFAULT sysdate  NULL ,
"F_CREATORUSERID" VARCHAR2(50 BYTE) NULL ,
"F_LASTMODIFYTIME" DATE NULL ,
"F_LASTMODIFYUSERID" VARCHAR2(50 BYTE) NULL ,
"F_DELETETIME" DATE NULL ,
"F_DELETEUSERID" VARCHAR2(500 BYTE) NULL ,
"F_PASSWORD" VARCHAR2(64 BYTE) NULL 
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_ACCOUNT" IS '账户';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_REALNAME" IS '姓名';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_NICKNAME" IS '呢称';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_HEADICON" IS '头像';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_GENDER" IS '性别';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_BIRTHDAY" IS '生日';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_MOBILEPHONE" IS '手机';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_EMAIL" IS '邮箱';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_WECHAT" IS '微信';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_MANAGERID" IS '主管主键';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_SECURITYLEVEL" IS '安全级别';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_SIGNATURE" IS '个性签名';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_ORGANIZEID" IS '组织主键';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_DEPARTMENTID" IS '部门主键';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_DUTYID" IS '岗位主键';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_JOBNUMBER" IS '人员工号';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_ISADMINISTRATOR" IS '是否管理员';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_SORTCODE" IS '排序码';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_DELETEMARK" IS '0 未删除   1 已删除';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_ENABLEDMARK" IS '1有效  0 无效';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_CREATORTIME" IS '创建时间';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_CREATORUSERID" IS '创建用户';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_LASTMODIFYTIME" IS '最后修改时间';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_LASTMODIFYUSERID" IS '最后修改用户';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_DELETETIME" IS '删除时间';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_DELETEUSERID" IS '删除用户';
COMMENT ON COLUMN "DTSCMS"."SYS_USER"."F_PASSWORD" IS '登录密码md5';

-- ----------------------------
-- Records of SYS_USER
-- ----------------------------
INSERT INTO "DTSCMS"."SYS_USER" VALUES ('1', 'admin', 'admin', 'admin', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '0', null, null, TO_DATE('2018-08-16 14:38:14', 'YYYY-MM-DD HH24:MI:SS'), null, null, null, null, null, 'e10adc3949ba59abbe56e057f20f883e');

-- ----------------------------
-- Indexes structure for table SYS_USER
-- ----------------------------

-- ----------------------------
-- Checks structure for table SYS_USER
-- ----------------------------
ALTER TABLE "DTSCMS"."SYS_USER" ADD CHECK ("F_ID" IS NOT NULL);
ALTER TABLE "DTSCMS"."SYS_USER" ADD CHECK ("F_ID" IS NOT NULL);
ALTER TABLE "DTSCMS"."SYS_USER" ADD CHECK ("F_ID" IS NOT NULL);

-- ----------------------------
-- Primary Key structure for table SYS_USER
-- ----------------------------
ALTER TABLE "DTSCMS"."SYS_USER" ADD PRIMARY KEY ("F_ID");
